### ISSUE TITLE
Media types exist after uninstall

### ISSUE THREAD

**Issue by XenHaloHalo** [s9e/XenForoMediaBBCodes#10]
When I have uninstalled the pack, the media types still exist when a user selects a media type. You can see in the image that the pack has been uninstalled because the embedding fails on non-Xenforo embedded types (in this case Flickr). How can I remove the specific S9E media types and just have the original XEN ones?

![capture](https://cloud.githubusercontent.com/assets/21128084/17836867/1e72e69a-6799-11e6-81f4-d29dd6c421bc.PNG)

**Comment by JoshyPHP** [comment]
Short URLs from the flic.kr domain are not supported, only full URLs from flicker.com.

If you uninstall the add-on, all the corresponding media sites are automatically uninstalled by XenForo. I've got to assume that the add-on was not properly uninstalled. If you don't see the add-on in the list of installed add-ons, try reinstalling and uninstalling it again. If it doesn't work, try XenForo's general support. Maybe they'll know why it works differently on your installation.
