### ISSUE TITLE
what could be wrong?

### ISSUE THREAD

**Issue by diomed** [s9e/XenForoMediaBBCodes#4]
hello.

I try embedding twitter, but everything is blank and nothing is showing. 
For others I get error that specified url cannot be embedded as media.

**Comment by s9e** [comment]
What is that Twitter URL that doesn't work? Is your forum public so that I can see for myself what this blank page is?

**Comment by diomed** [comment]
It's all good now. Probably it was the thing in cache, or something like that.

But strangely, when I try to insert IMDB ->this is the example of link that I use: http://www.imdb.com/title/tt2872718

or imgur: http://imgur.com/9eCUtUa

addon says that "The specified url cannot be embeded as media" 

WHY?

**Comment by s9e** [comment]
Only IMDb videos are embeddable, and only imgur albums and GIFV images. The list of supported URLs is available on the front page of this repository in [README.md](https://github.com/s9e/XenForoMediaBBCodes/blob/master/README.md).

Tumblr seems like a good fit so I'll consider adding it in an upcoming release.
