### ISSUE TITLE
Weather detection

### ISSUE THREAD

**Issue by cazzoo** [s9e/XenForoMediaBBCodes#5]
Hi there!

First of all, I would like to thank you for your great work you provide with this extension and the support you give to it.
Also, I wonder if it is possible to add some weather content to this plugin.
Examples : 
http://www.weather.com/weather/hourbyhour/l/UKXX3454:1:UK
http://www.lachainemeteo.com/meteo-royaume-uni/ville/previsions-meteo-donington-75555-0.php
http://www.accuweather.com/fr/gb/donington/pe11-4/weather-forecast/329077
https://weather.yahoo.com/united-kingdom/england/donington-18313/

Thanks

**Comment by s9e** [comment]
Weather maps don't really fit into the theme of embedded media but even if it did, it doesn't look like any of those can be embedded. Sorry, no can do.

**Comment by cazzoo** [comment]
Ok! Too bad this does not fit to embed media theme.
Thanks anyway for reply and for your work :)
