### ISSUE TITLE
Cannot override final method

### ISSUE THREAD

**Issue by bluemanos** [s9e/XenForoMediaBBCodes#7]
I just install the [latest veriosn](https://github.com/s9e/phpbb-ext-mediaembed/releases/download/20160204/s9e-mediaembed-20160204.zip) and it doesnt work for me.

I cannot create new thread/post and even preview them, because I'm getting Error 500. The log is saying:

```
[Thu Feb 18 10:11:18.642995 2016] [fcgid:warn] [pid 8482] [client 162.xxx.xxx.xxx:16736] mod_fcgid: stderr: PHP Fatal error:  Cannot override final method s9e\\TextFormatter\\Plugins\\ParserBase::__construct() in /var/www/clients/client3/web12/web/ext/s9e/mediaembed/parsing.php on line 1542, referer: http://xxx.xxx/posting.php?mode=post&f=13
```

My environment:

> PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
> Copyright (c) 1997-2014 The PHP Group
> Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
>     with XCache v3.1.0, Copyright (c) 2005-2013, by mOo
>     with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
>     with XCache Optimizer v3.1.0, Copyright (c) 2005-2013, by mOo
>     with XCache Cacher v3.1.0, Copyright (c) 2005-2013, by mOo
>     with XCache Coverager v3.1.0, Copyright (c) 2005-2013, by mOo
> 
> phpBB: 3.1.7-pl1
> MySQL: MySQL(i) 5.5.47-0ubuntu0.14.04.1

**Comment by JoshyPHP** [comment]
This PHP error is bogus; It's probably a bug in XCache, or possibly Zend OPcache. Actually, it's weird that you're using both OPcache *and* XCache at the same time. According to [this page](http://stackoverflow.com/a/28644014), a user of the same setup received similar errors so I guess it's a side-effect of using both opcode caches at the same time. Try disabling either of them and it should go away.

**Comment by bluemanos** [comment]
Thanks for the answer.

I disable the Zend OPcache and... the above problem disappear, but another error 500 appear :)
```
[Thu Feb 18 20:54:39.223166 2016] [fcgid:warn] [pid 23501] (104)Connection reset by peer: [client 162.xxx.xxx.xxx:16889] mod_fcgid: error reading data from FastCGI server, referer: https://xxxxxx.eu/posting.php?mode=post&f=4
[Thu Feb 18 20:54:39.223214 2016] [core:error] [pid 23501] [client 162.xxx.xxx.xxx:16889] End of script output before headers: posting.php, referer: https://xxxxxx.eu/posting.php?mode=post&f=4
```

**Comment by JoshyPHP** [comment]
I don't know what that error means but I'd be surprised if it was an issue with the code. Try disabling all of your opcode caches and optimizer extensions, that'll probably run better.
