### ISSUE TITLE
Steam Screenshots

### ISSUE THREAD

**Issue by Gr8z** [s9e/XenForoMediaBBCodes#8]
Links like this are common on our xenforo forum. Is it possible to embed these kinds of links ?

http://steamcommunity.com/sharedfiles/filedetails/?id=689119827
http://steamcommunity.com/sharedfiles/filedetails/?id=688952808
http://steamcommunity.com/sharedfiles/filedetails/?id=688842954

**Comment by JoshyPHP** [comment]
Steam doesn't seem to provide a way to embed content from this page, so I guess not. I'd recommend using a generic `[img]` BBCode to display the image.
