### ISSUE TITLE
VK.com video

### ISSUE THREAD

**Issue by fixator10** [s9e/XenForoMediaBBCodes#9]
![image](https://cloud.githubusercontent.com/assets/11073934/16011172/5d4209da-3195-11e6-91fa-9810e201a133.png)
![image](https://cloud.githubusercontent.com/assets/11073934/16011248/a4993722-3195-11e6-8e07-cb172454f627.png)
:arrow_up: From forum post
![2016-06-13 18-35-10](https://cloud.githubusercontent.com/assets/11073934/16011253/ab3fa5a2-3195-11e6-8e88-d7686eaaa109.png)
:arrow_up: From VK.com "share" feature.

Looks like VK require hash

**Comment by JoshyPHP** [comment]
The VK media site does extract the hash it requires, but in some situation your server may be unable to retrieve it. That can happen if your web server is unable to connect to VK's server. If you look inside your error log, there may be an entry that explains the issue.

**Comment by fixator10** [comment]
![image](https://cloud.githubusercontent.com/assets/11073934/16089573/d8fb17b2-333c-11e6-8e54-5eb1f1c3d869.png)
:arrow_up: XF show only that errors
Hosting errors contains only `Tue, 14 Jun 2016 22:45:17 -0500 AH00128: File does not exist: /home/vol3_4/byethost7.com/b7_17320283/htdocs/robots.txt` line

**Comment by fixator10** [comment]
_Accidentally closed issue, oops_

**Comment by JoshyPHP** [comment]
I guess you could try editing the PHP file and remove the `@` in `@file_get_contents` to unmute the error. Either way, this is an issue that can only be fixed on your side.

**Comment by fixator10** [comment]
After removing `@` i still have nothing in errors logs. So... May be, it's because i use free hosting. Whatever, thanks for support.
